version: '3'

services:
 ubuntu:
  build: ./ubuntu
  container_name: ubuntu_server
  ports:
   - "8080:8080"
  volumes:
   - ./project:/usr/src/project
  links:
   - mysql
  depends_on:
   - mysql
  privileged: true
  tty: true
 mysql:
  image: mysql:5.7.31
  container_name: ubuntu_mysql
  volumes:
   - ./mysql/sql:/docker-entrypoint-initdb.d
   - ./mysql/settings:/var/lib/mysql
  environment:
   MYSQL_DATABASE: spring_db
   MYSQL_USER: spring
   MYSQL_PASSWORD: spring
   MYSQL_ROOT_PASSWORD: root 
volumes:
  ubuntu-data:
